import time
from datetime import datetime
import csv
import os
import time
from numpy import genfromtxt



class Logger():
    def __init__(self):
        self.write_path = None

    def create_csv(self, filepath, filename, header_path='data\\header_20-01-2022_14-07-50.csv', with_header=False):
        """
        ‘r’	    Read        (default)	Open a file for read only
        ‘w’	    Write	    Open a file for write only (overwrite)
        ‘a’	    Append	    Open a file for write only (append)
        ‘r+’    Read+Write	open a file for both reading and writing
        ‘x’	    Create	    Create a new file
        """

        date_time = datetime.now().strftime("%d-%m-%Y_%H-%M-%S")
        self.write_path = os.path.join(filepath, filename + date_time + '.csv')

        #  TODO, check wheter faster encoding necessary, eg ascii possible
        connection = open(self.write_path, 'a', newline='', encoding='utf-8')
        csv_writer = csv.writer(connection)
        if with_header:
            header = genfromtxt(header_path, delimiter=",", dtype='str')
            csv_writer.writerow(header)
        connection.close()
        #connection.close() # TODO weglassen möglich?
        return self.write_path

    def write_line(self, line):
        with open(self.write_path, 'a', newline='\n', encoding='utf-8') as f:
            csv_writer = csv.writer(f)
            csv_writer.writerow(line)

# saved for easy usage: look at names and select which one you would like to get from client
node_ids = ['ns=6;s=::AsGlobalPV:bCutActive',
 'ns=6;s=::AsGlobalPV:CPU_Kuehler_Temp',
 'ns=6;s=::AsGlobalPV:CPU_Temp',
 'ns=6;s=::AsGlobalPV:CutCounter',
 'ns=6;s=::AsGlobalPV:CutTime',
 'ns=6;s=::AsGlobalPV:FFT_Anforderung',
 'ns=6;s=::AsGlobalPV:FlatstreamCutCounter',
 'ns=6;s=::AsGlobalPV:FlatstreamDone',
 'ns=6;s=::AsGlobalPV:fLichtschranke',
 'ns=6;s=::AsGlobalPV:FsMode_1Raw_2FftRaw_3FttHK',
 'ns=6;s=::AsGlobalPV:HebenAktiv',
 'ns=6;s=::AsGlobalPV:MotorAn',
 'ns=6;s=::AsGlobalPV:obereMaterialkante',
 'ns=6;s=::AsGlobalPV:P_Vorschub',
 'ns=6;s=::AsGlobalPV:Position',
 'ns=6;s=::AsGlobalPV:Position_Band',
 'ns=6;s=::AsGlobalPV:vVorschub',
 'ns=6;s=::AsGlobalPV:ZaehneProBand',
 'ns=6;s=::AsGlobalPV:FFT_HK1.value',
 'ns=6;s=::AsGlobalPV:FFT_HK1.freq',
 'ns=6;s=::AsGlobalPV:FFT_HK2.value',
 'ns=6;s=::AsGlobalPV:FFT_HK2.freq',
 'ns=6;s=::AsGlobalPV:FFT_HK3.value',
 'ns=6;s=::AsGlobalPV:FFT_HK3.freq',
 'ns=6;s=::AsGlobalPV:FFT_Raw1.value',
 'ns=6;s=::AsGlobalPV:FFT_Raw1.freq',
 'ns=6;s=::AsGlobalPV:FFT_Raw2.value',
 'ns=6;s=::AsGlobalPV:FFT_Raw2.freq',
 'ns=6;s=::AsGlobalPV:FFT_Raw3.value',
 'ns=6;s=::AsGlobalPV:FFT_Raw3.freq',
 'ns=6;s=::AsGlobalPV:PData.PEff',
 'ns=6;s=::AsGlobalPV:PData.CosPhi',
 'ns=6;s=::AsGlobalPV:PData.CutEnergy',
 'ns=6;s=::AsGlobalPV:Signal_Raw1.value',
 'ns=6;s=::AsGlobalPV:Signal_Raw1.time',
 'ns=6;s=::AsGlobalPV:Signal_Raw2.value',
 'ns=6;s=::AsGlobalPV:Signal_Raw2.time',
 'ns=6;s=::AsGlobalPV:Signal_Raw3.value',
 'ns=6;s=::AsGlobalPV:Signal_Raw3.time',
 'ns=6;s=::AsGlobalPV:TData.T1',
 'ns=6;s=::AsGlobalPV:TData.T2',
 'ns=6;s=::AsGlobalPV:TData.T3',
 'ns=6;s=::AsGlobalPV:TData.T4',
 'ns=6;s=::AsGlobalPV:Vib01.FrequencyBands',
 'ns=6;s=::AsGlobalPV:Vib01.RMS',
 'ns=6;s=::AsGlobalPV:Vib01.Peak',
 'ns=6;s=::AsGlobalPV:Vib01.CREST',
 'ns=6;s=::AsGlobalPV:Vib01.Skewness',
 'ns=6;s=::AsGlobalPV:Vib01.Kurtosis',
 'ns=6;s=::AsGlobalPV:Vib01.VDI3832',
 'ns=6;s=::AsGlobalPV:Vib02.FrequencyBands',
 'ns=6;s=::AsGlobalPV:Vib02.RMS',
 'ns=6;s=::AsGlobalPV:Vib02.Peak',
 'ns=6;s=::AsGlobalPV:Vib02.CREST',
 'ns=6;s=::AsGlobalPV:Vib02.Skewness',
 'ns=6;s=::AsGlobalPV:Vib02.Kurtosis',
 'ns=6;s=::AsGlobalPV:Vib02.VDI3832',
 'ns=6;s=::AsGlobalPV:Vib03.FrequencyBands',
 'ns=6;s=::AsGlobalPV:Vib03.RMS',
 'ns=6;s=::AsGlobalPV:Vib03.Peak',
 'ns=6;s=::AsGlobalPV:Vib03.CREST',
 'ns=6;s=::AsGlobalPV:Vib03.Skewness',
 'ns=6;s=::AsGlobalPV:Vib03.Kurtosis',
 'ns=6;s=::AsGlobalPV:Vib03.VDI3832',
 'ns=6;s=::AsGlobalPV:TData.T_IR']

node_ids_without_fftraw_ffthk_sigrawtime = ['ns=6;s=::AsGlobalPV:bCutActive',
 'ns=6;s=::AsGlobalPV:CPU_Kuehler_Temp',
 'ns=6;s=::AsGlobalPV:CPU_Temp',
 'ns=6;s=::AsGlobalPV:CutCounter',
 'ns=6;s=::AsGlobalPV:CutTime',
 'ns=6;s=::AsGlobalPV:FFT_Anforderung',
 'ns=6;s=::AsGlobalPV:FlatstreamCutCounter',
 'ns=6;s=::AsGlobalPV:FlatstreamDone',
 'ns=6;s=::AsGlobalPV:fLichtschranke',
 'ns=6;s=::AsGlobalPV:FsMode_1Raw_2FftRaw_3FttHK',
 'ns=6;s=::AsGlobalPV:HebenAktiv',
 'ns=6;s=::AsGlobalPV:MotorAn',
 'ns=6;s=::AsGlobalPV:obereMaterialkante',
 'ns=6;s=::AsGlobalPV:P_Vorschub',
 'ns=6;s=::AsGlobalPV:Position',
 'ns=6;s=::AsGlobalPV:Position_Band',
 'ns=6;s=::AsGlobalPV:vVorschub',
 'ns=6;s=::AsGlobalPV:ZaehneProBand',
 'ns=6;s=::AsGlobalPV:PData.PEff',
 'ns=6;s=::AsGlobalPV:PData.CosPhi',
 'ns=6;s=::AsGlobalPV:PData.CutEnergy',
 'ns=6;s=::AsGlobalPV:Signal_Raw1.value',
 'ns=6;s=::AsGlobalPV:Signal_Raw2.value',
 'ns=6;s=::AsGlobalPV:Signal_Raw3.value',
 'ns=6;s=::AsGlobalPV:TData.T1',
 'ns=6;s=::AsGlobalPV:TData.T2',
 'ns=6;s=::AsGlobalPV:TData.T3',
 'ns=6;s=::AsGlobalPV:TData.T4',
 'ns=6;s=::AsGlobalPV:Vib01.FrequencyBands',
 'ns=6;s=::AsGlobalPV:Vib01.RMS',
 'ns=6;s=::AsGlobalPV:Vib01.Peak',
 'ns=6;s=::AsGlobalPV:Vib01.CREST',
 'ns=6;s=::AsGlobalPV:Vib01.Skewness',
 'ns=6;s=::AsGlobalPV:Vib01.Kurtosis',
 'ns=6;s=::AsGlobalPV:Vib01.VDI3832',
 'ns=6;s=::AsGlobalPV:Vib02.FrequencyBands',
 'ns=6;s=::AsGlobalPV:Vib02.RMS',
 'ns=6;s=::AsGlobalPV:Vib02.Peak',
 'ns=6;s=::AsGlobalPV:Vib02.CREST',
 'ns=6;s=::AsGlobalPV:Vib02.Skewness',
 'ns=6;s=::AsGlobalPV:Vib02.Kurtosis',
 'ns=6;s=::AsGlobalPV:Vib02.VDI3832',
 'ns=6;s=::AsGlobalPV:Vib03.FrequencyBands',
 'ns=6;s=::AsGlobalPV:Vib03.RMS',
 'ns=6;s=::AsGlobalPV:Vib03.Peak',
 'ns=6;s=::AsGlobalPV:Vib03.CREST',
 'ns=6;s=::AsGlobalPV:Vib03.Skewness',
 'ns=6;s=::AsGlobalPV:Vib03.Kurtosis',
 'ns=6;s=::AsGlobalPV:Vib03.VDI3832',
 'ns=6;s=::AsGlobalPV:TData.T_IR']

ids = ['bCutActive',
 'CPU_Kuehler_Temp',
 'CPU_Temp',
 'CutCounter',
 'CutTime',
 'FFT_Anforderung',
 'FlatstreamCutCounter',
 'FlatstreamDone',
 'fLichtschranke',
 'FsMode_1Raw_2FftRaw_3FttHK',
 'HebenAktiv',
 'MotorAn',
 'obereMaterialkante',
 'P_Vorschub',
 'Position',
 'Position_Band',
 'vVorschub',
 'ZaehneProBand',
 'FFT_HK1.value',
 'FFT_HK1.freq',
 'FFT_HK2.value',
 'FFT_HK2.freq',
 'FFT_HK3.value',
 'FFT_HK3.freq',
 'FFT_Raw1.value',
 'FFT_Raw1.freq',
 'FFT_Raw2.value',
 'FFT_Raw2.freq',
 'FFT_Raw3.value',
 'FFT_Raw3.freq',
 'PData.PEff',
 'PData.CosPhi',
 'PData.CutEnergy',
 'Signal_Raw1.value',
 'Signal_Raw1.time',
 'Signal_Raw2.value',
 'Signal_Raw2.time',
 'Signal_Raw3.value',
 'Signal_Raw3.time',
 'T1 nach Zahn',
 'T2 vor Zahn',
 'TT3 getriebe defekt',
 'T4 hyd',
 'Vib01.FrequencyBands',
 'Vib01.RMS',
 'Vib01.Peak',
 'Vib01.CREST',
 'Vib01.Skewness',
 'Vib01.Kurtosis',
 'Vib01.VDI3832',
 'Vib02.FrequencyBands',
 'Vib02.RMS',
 'Vib02.Peak',
 'Vib02.CREST',
 'Vib02.Skewness',
 'Vib02.Kurtosis',
 'Vib02.VDI3832',
 'Vib03.FrequencyBands',
 'Vib03.RMS',
 'Vib03.Peak',
 'Vib03.CREST',
 'Vib03.Skewness',
 'Vib03.Kurtosis',
 'Vib03.VDI3832',
 'TData.T_IR',]

# added statuscode to the names
val_id_type_dict = {'bCutActive': bool,
 'CPU_Kuehler_Temp': int,
 'CPU_Temp': int,
 'CutCounter': int,
 'CutTime': float,
 'FFT_Anforderung': bool,
 'FlatstreamCutCounter': int,
 'FlatstreamDone': bool,
 'fLichtschranke': int,
 'FsMode_1Raw_2FftRaw_3FttHK': int,
 'HebenAktiv': bool,
 'MotorAn': bool,
 'obereMaterialkante': float,
 'P_Vorschub': float,
 'Position': float,
 'Position_Band': int,
 'vVorschub': float,
 'ZaehneProBand': int,
 'FFT_HK1.value': list,
 'FFT_HK1.freq': list,
 'FFT_HK2.value': list,
 'FFT_HK2.freq': list,
 'FFT_HK3.value': list,
 'FFT_HK3.freq': list,
 'FFT_Raw1.value': list,
 'FFT_Raw1.freq': list,
 'FFT_Raw2.value': list,
 'FFT_Raw2.freq': list,
 'FFT_Raw3.value': list,
 'FFT_Raw3.freq': list,
 'PData.PEff': float,
 'PData.CosPhi': float,
 'PData.CutEnergy': float,
 'Signal_Raw1.value': list,
 'Signal_Raw1.time': list,
 'Signal_Raw2.value': list,
 'Signal_Raw2.time': list,
 'Signal_Raw3.value': list,
 'Signal_Raw3.time': list,
 'TData.T1': float,
 'TData.T2': float,
 'TData.T3': float,
 'TData.T4': float,
 'Vib01.FrequencyBands': list,
 'Vib01.RMS': float,
 'Vib01.Peak': float,
 'Vib01.CREST': float,
 'Vib01.Skewness': float,
 'Vib01.Kurtosis': float,
 'Vib01.VDI3832': float,
 'Vib02.FrequencyBands': list,
 'Vib02.RMS': float,
 'Vib02.Peak': float,
 'Vib02.CREST': float,
 'Vib02.Skewness': float,
 'Vib02.Kurtosis': float,
 'Vib02.VDI3832': float,
 'Vib03.FrequencyBands': list,
 'Vib03.RMS': float,
 'Vib03.Peak': float,
 'Vib03.CREST': float,
 'Vib03.Skewness': float,
 'Vib03.Kurtosis': float,
 'Vib03.VDI3832': float,
 'TData.T_IR': float}


